apiVersion: v1
kind: Service
metadata:
  name: cv-to-ats
  namespace: manfred
  labels:
    app.kubernetes.io/name: cv-to-ats
    app.kubernetes.io/part-of: manfred
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cv-to-ats
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
